/* ============================================
   CEKIDOT MART — Extended Products Data
   5 items per category + full product detail
   ============================================ */

'use strict';

const PRODUCTS_EXTENDED = [

  /* ─── ELEKTRONIK (5) ─── */
  {
    id: 1,
    name: 'MacBook Pro M3 14" Space Black',
    price: 24500000,
    seller: 'TechStore ID',
    rating: 4.9,
    reviews: 128,
    condition: 'Baru',
    category: 'elektronik',
    location: 'Jakarta Selatan',
    img: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Laptop Apple dengan chip M3, layar Liquid Retina XDR 14", performa luar biasa untuk profesional kreatif.',
    funsi: 'Laptop profesional untuk desain grafis, video editing, coding, dan multitasking berat.',
    manfaat: 'Meningkatkan produktivitas kerja dengan performa tinggi, baterai tahan seharian, dan ekosistem Apple yang seamless.',
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max 256GB Natural Titanium',
    price: 18900000,
    seller: 'Apple Center',
    rating: 4.8,
    reviews: 94,
    condition: 'Baru',
    category: 'elektronik',
    location: 'Bandung',
    img: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Flagship iPhone dengan chip A17 Pro, kamera 48MP, Dynamic Island, dan body titanium premium.',
    funsi: 'Smartphone serbaguna untuk komunikasi, fotografi, gaming mobile, dan produktivitas harian.',
    manfaat: 'Kamera setara kamera profesional, koneksi super cepat, dan keamanan data terbaik di kelasnya.',
  },
  {
    id: 7,
    name: 'Samsung Galaxy Tab S9 Ultra 12GB',
    price: 16500000,
    seller: 'GadgetPlus',
    rating: 4.7,
    reviews: 62,
    condition: 'Baru',
    category: 'elektronik',
    location: 'Tangerang',
    img: 'https://images.unsplash.com/photo-1590739000027-286c2688ee57?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Tablet Android terkencang dengan layar AMOLED 14.6", stylus S-Pen, dan RAM 12GB.',
    funsi: 'Tablet multifungsi untuk menggambar digital, presentasi, streaming, belajar online, dan bekerja di mana saja.',
    manfaat: 'Menggantikan laptop untuk pekerjaan ringan-menengah, ideal untuk content creator dan pelajar.',
  },
  {
    id: 8,
    name: 'Mechanical Keyboard Keychron K8 Pro',
    price: 1850000,
    seller: 'TechGear_ID',
    rating: 4.8,
    reviews: 89,
    condition: 'Baru',
    category: 'elektronik',
    location: 'Jakarta Barat',
    img: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Keyboard mekanikal tenkeyless wireless dengan switch Gateron Pro, RGB backlight, kompatibel Mac & Windows.',
    funsi: 'Keyboard untuk mengetik, coding, gaming, dan setup workstation profesional.',
    manfaat: 'Meningkatkan kenyamanan dan kecepatan mengetik, mengurangi kelelahan tangan dalam jangka panjang.',
  },
  {
    id: 9,
    name: 'Sony WH-1000XM5 Wireless ANC Headphone',
    price: 4500000,
    seller: 'AudioPro ID',
    rating: 4.9,
    reviews: 201,
    condition: 'Baru',
    category: 'elektronik',
    location: 'Jakarta Pusat',
    img: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Headphone over-ear dengan Active Noise Cancelling terbaik di kelasnya, 30 jam baterai, dan audio Hi-Res.',
    funsi: 'Headphone untuk mendengarkan musik, panggilan video/telepon, kerja dari rumah, dan perjalanan jauh.',
    manfaat: 'Memblokir kebisingan sekitar agar lebih fokus bekerja, menikmati musik berkualitas studio di mana pun.',
  },

  /* ─── FASHION (5) ─── */
  {
    id: 3,
    name: 'Nike Air Jordan 1 Retro High OG',
    price: 3200000,
    seller: 'SneakerHeadJKT',
    rating: 4.7,
    reviews: 56,
    condition: 'Baru',
    category: 'fashion',
    location: 'Jakarta Pusat',
    img: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Sneakers ikonik Nike Air Jordan 1 Retro High OG colorway terbaru, sol Air, dan upper kulit premium.',
    funsi: 'Alas kaki kasual dan streetwear yang stylish untuk aktivitas sehari-hari maupun koleksi.',
    manfaat: 'Kenyamanan sepanjang hari, meningkatkan penampilan, dan nilai koleksi yang berpotensi naik.',
  },
  {
    id: 10,
    name: 'Uniqlo Ultra Light Down Jacket',
    price: 699000,
    seller: 'FashionMall ID',
    rating: 4.6,
    reviews: 145,
    condition: 'Baru',
    category: 'fashion',
    location: 'Surabaya',
    img: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Jaket bulu ringan ekstra dari Uniqlo, bisa dilipat menjadi pouch kecil, tersedia banyak warna.',
    funsi: 'Jaket penghangat ringan untuk udara dingin, perjalanan, naik gunung ringan, atau ruangan ber-AC.',
    manfaat: 'Praktis dibawa ke mana saja karena sangat ringan dan kompak, tetap hangat tanpa terasa berat.',
  },
  {
    id: 11,
    name: 'Adidas Stan Smith Vegan Putih',
    price: 1200000,
    seller: 'OriginalKicks',
    rating: 4.5,
    reviews: 78,
    condition: 'Baru',
    category: 'fashion',
    location: 'Bandung',
    img: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Sneakers klasik Adidas Stan Smith edisi Vegan dengan bahan ramah lingkungan, desain timeless.',
    funsi: 'Sepatu kasual serbaguna yang cocok dipadukan dengan berbagai outfit, dari formal casual hingga sporty.',
    manfaat: 'Desain abadi yang tidak ketinggalan zaman, nyaman dipakai seharian, dan ramah lingkungan.',
  },
  {
    id: 12,
    name: 'Kemeja Flannel Premium Pria Oversize',
    price: 285000,
    seller: 'UrbanThreads',
    rating: 4.4,
    reviews: 203,
    condition: 'Baru',
    category: 'fashion',
    location: 'Yogyakarta',
    img: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Kemeja flannel motif kotak-kotak oversize bahan tebal premium, cocok untuk semua musim.',
    funsi: 'Atasan kasual untuk aktivitas sehari-hari, hangout, atau dipakai sebagai outer di atas kaos.',
    manfaat: 'Serbaguna dan mudah dipadukan, bahan hangat dan nyaman dipakai dalam berbagai situasi.',
  },
  {
    id: 13,
    name: 'Tas Ransel Laptop Thule Lithos 20L',
    price: 1750000,
    seller: 'BagHouse Premium',
    rating: 4.8,
    reviews: 112,
    condition: 'Baru',
    category: 'fashion',
    location: 'Jakarta Selatan',
    img: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Tas ransel 20L dari Thule dengan kompartemen laptop khusus, water-resistant, dan ergonomis.',
    funsi: 'Tas multifungsi untuk membawa laptop, buku, perlengkapan kerja, atau traveling ringan.',
    manfaat: 'Melindungi laptop dan barang bawaan, nyaman di punggung seharian, tahan cuaca.',
  },

  /* ─── GAMING (5) ─── */
  {
    id: 4,
    name: 'PlayStation 5 Digital Edition Bundle',
    price: 8500000,
    seller: 'GamingZone99',
    rating: 4.6,
    reviews: 73,
    condition: 'Baru',
    category: 'gaming',
    location: 'Surabaya',
    img: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Konsol gaming Sony PS5 edisi Digital tanpa disc, SSD 825GB, resolusi 4K, frame rate hingga 120fps.',
    funsi: 'Konsol gaming generasi terbaru untuk memainkan game AAA eksklusif PlayStation dan hiburan multimedia.',
    manfaat: 'Pengalaman gaming imersif dengan loading super cepat (SSD), grafis memukau, dan audio 3D.',
  },
  {
    id: 14,
    name: 'Nintendo Switch OLED Mario Bundle',
    price: 5200000,
    seller: 'NintendoShop ID',
    rating: 4.9,
    reviews: 167,
    condition: 'Baru',
    category: 'gaming',
    location: 'Jakarta Selatan',
    img: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Nintendo Switch versi layar OLED 7 inci, bisa dimainkan di TV, tabletop, maupun genggam.',
    funsi: 'Konsol hybrid yang bisa digunakan di rumah maupun bepergian, cocok untuk semua usia.',
    manfaat: 'Fleksibilitas bermain kapan dan di mana saja, library game Nintendo yang unik dan eksklusif.',
  },
  {
    id: 15,
    name: 'Logitech G Pro X Gaming Headset',
    price: 1950000,
    seller: 'GameGear Pro',
    rating: 4.7,
    reviews: 94,
    condition: 'Baru',
    category: 'gaming',
    location: 'Medan',
    img: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Headset gaming esports dengan driver PRO-G 50mm, mikrofon Blue VO!CE detachable, surround 7.1.',
    funsi: 'Headset untuk gaming kompetitif, komunikasi tim, dan streaming.',
    manfaat: 'Suara jernih dan detail membantu deteksi musuh lebih akurat, mikrofon studio-quality untuk komunikasi.',
  },
  {
    id: 16,
    name: 'Xbox Series X 1TB Console',
    price: 9200000,
    seller: 'XboxCenter ID',
    rating: 4.5,
    reviews: 48,
    condition: 'Baru',
    category: 'gaming',
    location: 'Bali',
    img: 'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Konsol gaming Microsoft paling powerful, 4K @ 60fps (hingga 120fps), Quick Resume, Xbox Game Pass.',
    funsi: 'Konsol gaming untuk memainkan ribuan judul game via Xbox Game Pass dan backward compatibility.',
    manfaat: 'Akses ribuan game dengan berlangganan, performa 4K, dan kompatibilitas dengan game Xbox lama.',
  },
  {
    id: 17,
    name: 'Razer DeathAdder V3 Gaming Mouse',
    price: 1100000,
    seller: 'TechGear_ID',
    rating: 4.8,
    reviews: 233,
    condition: 'Baru',
    category: 'gaming',
    location: 'Tangerang',
    img: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Mouse gaming ergonomis dengan sensor Focus Pro 30K, klik optik, 59g ultra-ringan.',
    funsi: 'Mouse presisi tinggi untuk gaming FPS/MOBA kompetitif dan pekerjaan sehari-hari.',
    manfaat: 'Akurasi kursor luar biasa untuk memenangkan pertandingan, ergonomi mengurangi kelelahan tangan.',
  },

  /* ─── KENDARAAN (5) ─── */
  {
    id: 5,
    name: 'Honda Vario 160 2023 Low KM',
    price: 22000000,
    seller: 'AutoDealer Prima',
    rating: 4.5,
    reviews: 31,
    condition: 'Bekas',
    category: 'kendaraan',
    location: 'Bekasi',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop',
    badge: 'used',
    shortDesc: 'Honda Vario 160 2023 kilometer rendah, mesin 160cc ESP+, ABS, CBS, dan fitur keyless.',
    funsi: 'Sepeda motor matik komuter harian dengan performa dan fitur modern.',
    manfaat: 'Irit bahan bakar, fitur keamanan canggih, nilai jual kembali tinggi, dan nyaman untuk jarak jauh.',
  },
  {
    id: 18,
    name: 'Yamaha NMAX 155 Connected 2024',
    price: 34500000,
    seller: 'YamahaDealer Jkt',
    rating: 4.7,
    reviews: 45,
    condition: 'Baru',
    category: 'kendaraan',
    location: 'Jakarta Timur',
    img: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Yamaha NMAX 155 terbaru dengan fitur konektivitas smartphone, ABS, traction control, dan Y-Connect.',
    funsi: 'Skuter premium untuk komuter harian dan touring jarak menengah dengan fitur teknologi terkini.',
    manfaat: 'Koneksi smartphone via app, notifikasi real-time, perjalanan lebih aman dengan ABS dan traction control.',
  },
  {
    id: 19,
    name: 'Sepeda Polygon Strattos S5 2023',
    price: 8900000,
    seller: 'BikeWorld ID',
    rating: 4.6,
    reviews: 29,
    condition: 'Baru',
    category: 'kendaraan',
    location: 'Surabaya',
    img: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Sepeda road bike Polygon Strattos S5 dengan rangka aluminium, groupset Shimano 105, rem hidraulik.',
    funsi: 'Sepeda balap/road bike untuk olahraga, touring, dan komuter dengan performa tinggi.',
    manfaat: 'Berolahraga sambil commute, ramah lingkungan, meningkatkan kebugaran, dan bebas macet.',
  },
  {
    id: 20,
    name: 'Honda Beat Street 2022 Bekas Mulus',
    price: 14500000,
    seller: 'MotorMurah99',
    rating: 4.3,
    reviews: 18,
    condition: 'Bekas',
    category: 'kendaraan',
    location: 'Semarang',
    img: 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=400&h=300&fit=crop',
    badge: 'used',
    shortDesc: 'Honda Beat Street 2022 warna special edition, kondisi mulus, jarang dipakai, kilometer 8.000.',
    funsi: 'Motor matik irit untuk keperluan harian, belanja, dan aktivitas dalam kota.',
    manfaat: 'Irit BBM hingga 59 km/L, lincah di kemacetan, harga terjangkau dengan kondisi prima.',
  },
  {
    id: 21,
    name: 'Vespa Primavera 150 iGet 2023',
    price: 49000000,
    seller: 'VespaGalleria',
    rating: 4.8,
    reviews: 22,
    condition: 'Baru',
    category: 'kendaraan',
    location: 'Bali',
    img: 'https://images.unsplash.com/photo-1558981285-6f0c8d5eb2d4?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Vespa Primavera 150cc edisi terbaru, mesin iGet 3 katup, desain ikonik Italia, body baja.',
    funsi: 'Skuter premium bergaya Italia untuk berkendara harian dengan sentuhan mewah dan elegan.',
    manfaat: 'Gaya hidup premium, mudah parkir, nilai seni tinggi, dan komunitas Vespa yang aktif di Indonesia.',
  },

  /* ─── FURNITURE (5) ─── */
  {
    id: 6,
    name: 'Kursi Gaming RESPAWN 900 Full Recline',
    price: 2800000,
    seller: 'FurnitureMall',
    rating: 4.4,
    reviews: 44,
    condition: 'Baru',
    category: 'furniture',
    location: 'Depok',
    img: 'https://images.unsplash.com/photo-1616627985067-55ea1b5cf016?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Kursi gaming dengan sandaran 180° full recline, bantal lumbar, footrest, dan bahan PU leather premium.',
    funsi: 'Kursi untuk gaming marathon, bekerja dari rumah, atau bersantai dengan posisi yang nyaman.',
    manfaat: 'Mengurangi nyeri punggung saat duduk lama, sandaran penuh untuk istirahat, meningkatkan fokus.',
  },
  {
    id: 22,
    name: 'Meja Kerja Standing Desk Motorized',
    price: 4200000,
    seller: 'ErgoHome ID',
    rating: 4.7,
    reviews: 67,
    condition: 'Baru',
    category: 'furniture',
    location: 'Jakarta Selatan',
    img: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Meja standing desk elektrik dengan motor dual, ketinggian 70-120cm, memori 4 posisi, anti-collision.',
    funsi: 'Meja kerja yang bisa diatur tingginya untuk bekerja sambil berdiri maupun duduk.',
    manfaat: 'Mengurangi risiko penyakit akibat duduk terlalu lama, meningkatkan energi dan produktivitas kerja.',
  },
  {
    id: 23,
    name: 'Rak Buku Dinding Minimalis Kayu Jati',
    price: 1350000,
    seller: 'WoodCraft ID',
    rating: 4.6,
    reviews: 88,
    condition: 'Baru',
    category: 'furniture',
    location: 'Jepara',
    img: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Rak dinding floating shelf dari kayu jati solid, 3 tingkat, ukuran 80x25x15cm, finishing natural.',
    funsi: 'Penyimpanan dan display buku, dekorasi, tanaman, atau koleksi di dinding ruang tamu/kamar.',
    manfaat: 'Menghemat lantai, memperindah ruangan, dan mengorganisir barang dengan estetika natural.',
  },
  {
    id: 24,
    name: 'Sofa L-Shape Premium Fabric 3+2 Seater',
    price: 7800000,
    seller: 'HomeLiving Store',
    rating: 4.5,
    reviews: 33,
    condition: 'Baru',
    category: 'furniture',
    location: 'Tangerang Selatan',
    img: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Sofa sudut L-Shape 5 dudukan dengan fabric premium anti-noda, busa high-density, kaki kayu solid.',
    funsi: 'Furnitur ruang tamu untuk duduk, bersantai, nonton TV, atau berkumpul bersama keluarga.',
    manfaat: 'Kenyamanan maksimal untuk keluarga, mengoptimalkan pojok ruang tamu, tahan lama dan mudah dibersihkan.',
  },
  {
    id: 25,
    name: 'Lemari Pakaian 4 Pintu Sliding Mirror',
    price: 5500000,
    seller: 'FurnitureMall',
    rating: 4.4,
    reviews: 51,
    condition: 'Baru',
    category: 'furniture',
    location: 'Bekasi',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&sat=-100',
    badge: '',
    shortDesc: 'Lemari 4 pintu sliding dengan cermin full-length, rak dalam lengkap, material MDF lapis veneer.',
    funsi: 'Penyimpanan pakaian, sepatu, dan aksesoris dengan cermin besar untuk merapikan penampilan.',
    manfaat: 'Mengorganisir pakaian secara rapi, cermin besar menghemat ruang, estetika minimalis modern.',
  },

  /* ─── RANDOM STUFF (5) ─── */
  {
    id: 26,
    name: 'Air Fryer Philips HD9252 4.1L',
    price: 1299000,
    seller: 'KitchenMart ID',
    rating: 4.8,
    reviews: 312,
    condition: 'Baru',
    category: 'random',
    location: 'Jakarta Pusat',
    img: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Air fryer Philips 4.1L Rapid Air technology, 7 preset masak, timer 60 menit, 1400W.',
    funsi: 'Alat masak serbaguna untuk menggoreng, memanggang, memanggang, dan memanaskan makanan.',
    manfaat: 'Masak lebih sehat dengan sedikit/tanpa minyak, hemat waktu, dan mudah dibersihkan.',
  },
  {
    id: 27,
    name: 'Kamera Polaroid Now+ Gen 2',
    price: 1450000,
    seller: 'CameraClick',
    rating: 4.6,
    reviews: 89,
    condition: 'Baru',
    category: 'random',
    location: 'Yogyakarta',
    img: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=400&h=300&fit=crop',
    badge: 'new',
    shortDesc: 'Kamera instan Polaroid terbaru dengan 5 mode kreatif, double exposure, self-timer, dan Bluetooth.',
    funsi: 'Kamera instan untuk mencetak foto langsung, journaling, dekorasi, dan kenangan fisik.',
    manfaat: 'Mengabadikan momen spesial menjadi foto fisik instan, hadiah unik, dan ekspresi kreatif.',
  },
  {
    id: 28,
    name: 'Ukulele Soprano Mahogany Kala KA-15S',
    price: 850000,
    seller: 'MusicStore ID',
    rating: 4.7,
    reviews: 64,
    condition: 'Baru',
    category: 'random',
    location: 'Bali',
    img: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Ukulele soprano 21" kayu mahogany solid dari Kala, sudah include gig bag dan tuner clip-on.',
    funsi: 'Instrumen musik ringan untuk belajar bermain ukulele, menghibur diri, atau pentas musik.',
    manfaat: 'Lebih mudah dipelajari dari gitar, portabel, suara khas yang menenangkan, dan melatih kreativitas.',
  },
  {
    id: 29,
    name: 'Tenda Camping Naturehike Cloud-Up 3',
    price: 1750000,
    seller: 'OutdoorGear ID',
    rating: 4.9,
    reviews: 148,
    condition: 'Baru',
    category: 'random',
    location: 'Bandung',
    img: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=400&h=300&fit=crop',
    badge: 'hot',
    shortDesc: 'Tenda ultralight 3 orang dari Naturehike, double layer, tahan angin & hujan, berat hanya 1.8kg.',
    funsi: 'Tenda untuk berkemah, mendaki gunung, festival outdoor, atau petualangan alam terbuka.',
    manfaat: 'Ringan dan kompak untuk dibawa mendaki, tahan cuaca ekstrem, setup cepat kurang dari 10 menit.',
  },
  {
    id: 30,
    name: 'Diffuser Aromaterapi + 6 Essential Oil Set',
    price: 399000,
    seller: 'WellnessHome',
    rating: 4.5,
    reviews: 267,
    condition: 'Baru',
    category: 'random',
    location: 'Solo',
    img: 'https://images.unsplash.com/photo-1611071536428-82a00d3783b0?w=400&h=300&fit=crop',
    badge: '',
    shortDesc: 'Diffuser ultrasonic 300ml kayu bambu dengan 7 warna LED, auto-off, + 6 botol essential oil.',
    funsi: 'Alat aromaterapi untuk menyebarkan wangi essential oil di ruangan, humidifier udara ringan.',
    manfaat: 'Menciptakan suasana rileks di rumah, membantu tidur lebih nyenyak, dan menjaga kelembaban udara.',
  },
];

// Override global PRODUCTS dengan data lengkap
window.PRODUCTS = PRODUCTS_EXTENDED;

// Expose globally
window.PRODUCTS_EXTENDED = PRODUCTS_EXTENDED;
